DROP TABLE IF EXISTS user;
CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE books (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    書名 TEXT NOT NULL,
    ISBN TEXT NOT NULL UNIQUE,
    作者 TEXT NOT NULL,
    版本 TEXT NOT NULL,
    出版年份 INTEGER NOT NULL,
    書本類別 TEXT NOT NULL,
    價格 REAL NOT NULL,
    書況 TEXT NOT NULL,
    posted_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
);